In [1]:
import numpy as np

In [2]:
sud =  [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

In [3]:
def constraints(row,column,num):
    global sud
    for i in range(0,9):
        if sud[row][i]==num:
                return False
    for i in range(0,9):
        if sud[i][column]==num:
                return False
                
        
    x=((column)//3)*3
    y=((row)//3)*3
    for i in range(0,3):
        for j in range(0,3):
            if sud[y+i][x+j]==num:
                return False
        
    return True

In [4]:
def solve():
    global sud
    for row in range(0,9):
        for column in range(0,9):
            if sud[row][column]==0:
                for num in range(1,10):
                    if constraints(row,column,num):
                        sud[row][column]=num
                        solve() #keep solving with next value of num
                        sud[row][column]=0  
                return
    print(np.matrix(sud))
    input('More possible solutions press "Enter" ')
solve()

[[5 3 4 6 7 8 1 9 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 9 7 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 7 1 9]]
More possible solutions press "Enter" 
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]
More possible solutions press "Enter" 
